import React, { useState } from "react";
import "./Verification.sass";

const Verification = () => {
    const [code, setCode] = useState("");

    const verify = (e) => {
        e.preventDefault();

        alert("Verify.");
    };

    const resendSms = (e) => {
        e.preventDefault();

        alert("Resend SMS.");
    };

    const disabled = code.length !== 0;

    return (
        <div className="verification-container">
            <h1 className="verification-title">2-STEP VERIFICATION</h1>
            <form className="verification-form" onSubmit={verify} noValidate>
                <p className="verification-instruction">
                    Enter the verification code generated by your phone ending
                    in <span style={{ fontWeight: "bold" }}>+123123123</span>.
                </p>
                <input
                    placeholder="Confirmation Code"
                    id="code"
                    name="code"
                    type="number"
                    value={code}
                    onChange={(e) => setCode(e.target.value)}
                    className={
                        code.length === 0 ? "code-input" : "code-input-filled"
                    }
                />
                <p className="didnt-get-code" onClick={resendSms}>
                    I didn't get the code. Resend SMS.
                </p>
                <button
                    type="submit"
                    disabled={!disabled}
                    className="verification-button"
                >
                    VERIFY
                </button>
            </form>
        </div>
    );
};

export default Verification;
